version: '3'

services:
  proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    command: bash -c "sed -i '/{% include \"_hsts_map.conf\" %}/d' /app/templates/_location.conf; while true; do sleep 86400; done"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./.docker/proxy_data:/data
      - ./.docker/letsencrypt:/etc/letsencrypt
    # networks:
    #   - test-networks
